swagger: '2.0'
info:
  title: Timeslots Information and Booking API
  description: Service to handle timeslot information and bookings for a dental clinic
  version: 1.0.0
host: 192.168.99.100:9998
basePath: /v1
schemes:
  - https
  - http
paths:
  /timeslots:
    get:
      summary: Returns a list of available timeslots.
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      tags:
        - Timeslots
    post:
      summary: Adds a new dentist with fresh timeslots
      parameters:
        - in: body
          name: timeslot
          description: The dentist to add
          schema:
            type: object
            required:
              - dentistID
            properties:
              dentistID:
                type: integer
      tags:
        - Timeslots
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '409':
          description: Timeslot already exists
        
  '/timeslots/{dentistID}':
    get:
      summary: Returns available timeslots of a given dentist ID
      parameters:
        - in: path
          name: dentistID
          required: true
          type: integer
          minimum: 1
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '404':
          description: Timeslot not found
      tags:
        - Timeslots
    post:
      summary: Adds a new timeslot for a given dentist ID
      parameters:
        - in: path
          name: dentistID
          required: true
          type: integer
          minimum: 1
        - in: body
          name: timeslot
          description: The timeslot to add
          schema:
            type: object
            required:
              - startTime
            properties:
              startTime:
                type: integer
      tags:
        - Timeslots
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '409':
          description: Timeslot already exists
  '/timeslots/{dentistID}/{timeslotID}':
    get:
      summary: Returns timeslot information of a given timeslot ID
      description: timeslotID is not the same as startTime. timeslotID gives the actual id of the booking from the start of the day e.g. appointment at 8 makes timeslotID 1 as it is the 1st booking of the day.
      parameters:
        - in: path
          name: dentistID
          required: true
          type: integer
          minimum: 1
        - in: path
          name: timeslotID
          required: true
          type: integer
          minimum: 1
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '404':
          description: Timeslot not found
      tags:
        - Timeslots
  '/timeslots/{dentistID}/{timeslotID}/reserve':
    put:
      summary: Reserves a timeslot of given timeslot ID for a given dentist ID
      parameters:
        - in: path
          name: dentistID
          required: true
          type: integer
          description: ID of the dentist to be booked
          minimum: 1
        - in: path
          name: timeslotID
          description: timeslotID of the time the dentist is to be booked
          required: true
          type: integer
          minimum: 1
      tags:
        - Timeslots
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '404':
          description: Timeslot not found
  '/timeslots/{dentistID}/{timeslotID}/cancel':
    put:
      summary: Cancel a timeslot of given timeslot ID for a given dentist ID
      parameters:
        - in: path
          name: dentistID
          required: true
          type: integer
          description: ID of the dentist to be booked
          minimum: 1
        - in: path
          name: timeslotID
          description: timeslotID of the time the dentist is to be booked
          required: true
          type: integer
          minimum: 1
      tags:
        - Timeslots
      produces:
        - application/json
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID supplied
        '404':
          description: Timeslot not found
