swagger: "2.0"
info:
  title: Webhook API
  description: Webhook to handle API calls
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
  - http
paths:
  /webhook:
    post:
      summary: Handles request from Dialogflow

      tags: 
        - Webhook
      produces:
        - application/json
      responses:
        200:
          description: OK
        405:
          description: "Invalid input"